/**
 * Resource loader registration — import this module once to populate the registry.
 *
 * Note: KnowledgeInstructionsLoader, DocSaveInstructionsLoader, and
 * SessionTitleInstructionsLoader are now auto-generated by the AgentAction system.
 * See src/lib/agent-actions/ — importing that module registers them automatically.
 */

import { resourceRegistry } from '../resource-registry';
import { ContextResourceLoader } from './context-loader';
import { ContextIndexLoader } from './context-index-loader';
import { DesignDocsIndexLoader } from './design-docs-index-loader';
import { ActiveTasksLoader } from './active-tasks-loader';
import { SuspendedTasksLoader } from './suspended-tasks-loader';
import { AvailableAgentsLoader } from './available-agents-loader';
import { SystemPromptLoader } from './system-prompt-loader';
import { TodoListLoader } from './todo-list-loader';
import { InlineTextLoader } from './inline-text-loader';
import {
  FlowContextLoader,
  ReferenceTurnsLoader,
} from './static-text-loader';

resourceRegistry.register(new ContextResourceLoader());
resourceRegistry.register(new ContextIndexLoader());
resourceRegistry.register(new DesignDocsIndexLoader());
resourceRegistry.register(new ActiveTasksLoader());
resourceRegistry.register(new SuspendedTasksLoader());
resourceRegistry.register(new AvailableAgentsLoader());
resourceRegistry.register(new SystemPromptLoader());
resourceRegistry.register(new TodoListLoader());
resourceRegistry.register(new InlineTextLoader());
resourceRegistry.register(new FlowContextLoader());
resourceRegistry.register(new ReferenceTurnsLoader());
