/**
 * Static text loaders — fixed prompt sections that don't depend on external data.
 *
 * Note: KnowledgeInstructionsLoader, DocSaveInstructionsLoader, and
 * SessionTitleInstructionsLoader have been migrated to the AgentAction system.
 * Their ResourceLoaders are now auto-generated by AgentActionRegistry.
 * See src/lib/agent-actions/ for the new implementations.
 *
 * Remaining loaders:
 * - FlowContextLoader: project flow context section
 * - ReferenceTurnsLoader: imported conversation turns (guest agent)
 */

import type { ResourceLoader, LoaderContext } from '../resource-loader';
import type { ResourceRef, ResolvedResource, FlowContextRef, ReferenceTurnsRef } from '@/types/resource';

// ── Flow Context ──

export class FlowContextLoader implements ResourceLoader {
  readonly type = 'flow-context' as const;

  async resolve(ref: ResourceRef, _ctx: LoaderContext): Promise<ResolvedResource> {
    const fcRef = ref as FlowContextRef;
    const { projectKey, projectName, flowDataPath } = fcRef;
    if (!projectKey) {
      return { ref, content: '', ok: false };
    }

    const legacyPathLine = flowDataPath
      ? `\n\n（旧版）项目 Flow JSON 路径：${flowDataPath}（产品已下线，请勿依赖该文件。）`
      : '';

    const content = `你正在协助管理项目「${projectName}」（key: ${projectKey}）。

项目注册信息位于用户数据目录下的 projects/index.json；不再使用 per-project Flow 看板 JSON。若需任务与上下文，请使用待办、会话与文档域。${legacyPathLine}`;

    return {
      ref,
      content,
      sectionTitle: '当前项目上下文',
      ok: true,
    };
  }
}

// ── Reference Turns (Guest Agent) ──

export class ReferenceTurnsLoader implements ResourceLoader {
  readonly type = 'reference-turns' as const;

  async resolve(ref: ResourceRef, _ctx: LoaderContext): Promise<ResolvedResource> {
    const rtRef = ref as ReferenceTurnsRef;
    const turns = rtRef.turns;
    if (!turns || turns.length === 0) {
      return { ref, content: '', ok: true };
    }

    const turnsText = turns.map((t, i) => {
      const roleLabel = t.role === 'user' ? '用户' : 'AI';
      return `### 轮次 ${i + 1}（${roleLabel}）\n${t.content}`;
    }).join('\n\n');

    const content = `以下是来自另一个 AI 会话的对话记录，用户希望你基于这些内容进行讨论（如讲解、分析等）。
这些内容仅供参考，你不需要继续执行其中的操作。

${turnsText}`;

    return {
      ref,
      content,
      sectionTitle: '参考对话',
      ok: true,
    };
  }
}
